package pipeprt.gui.widgets;

import java.awt.Color;
import java.util.Enumeration;

import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.event.CaretListener;

import pipeprt.dataLayer.DataLayerInterface;
import pipeprt.dataLayer.PipeTransition;
import pipeprt.dataLayer.RateParameter;
import pipeprt.gui.GuiView;
import pipeprtlocales.PipePrTLocales;


/**
 *
 * @author  pere
 */
public class TransitionEditorPanel
        extends javax.swing.JPanel {
   
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
PipeTransition transition;
   boolean attributesVisible;
   boolean timed;
   boolean infiniteServer;
   Integer priority = 0;
   Double rate;
   String name;   
   RateParameter rParameter;
   DataLayerInterface pnmlData;
   GuiView view;
   JRootPane rootPane;
   
   /**
    * Creates new form PlaceEditor
    */
   public TransitionEditorPanel(JRootPane _rootPane, PipeTransition _transition,
           DataLayerInterface _pnmlData, GuiView _view) {
      transition = _transition;
      pnmlData = _pnmlData;
      view = _view;
      rParameter = transition.getRateParameter();
      name = transition.getName();
      timed = transition.isTimed();
      infiniteServer = transition.isInfiniteServer();
      rootPane = _rootPane;
      
      initComponents();
      
      this.serverLabel.setVisible(false);
      this.serverPanel.setVisible(false);
      
      rootPane.setDefaultButton(okButton);

      attributesVisible = transition.getAttributesVisible();
      
      rate = transition.getRate();

      if (timed){
         timedTransition();
      } else {
         immediateTransition();
         priority = _transition.getPriority();
      }
      
      if (infiniteServer) {
         infiniteServerRadioButton.setSelected(true);
      } else {
         singleServerRadioButton.setSelected(true);
      }
      
      
      if (rParameter != null){
         for (int i = 1; i < rateComboBox.getItemCount(); i++) {
            if (rParameter == (RateParameter)rateComboBox.getItemAt(i)){
               rateComboBox.setSelectedIndex(i);
            }
         }
      }      
   }
   
   
   private void timedTransition(){
      timedRadioButton.setSelected(true);
      
      rateLabel.setText("Rate:");
      rateTextField.setText("" + transition.getRate());
      
      prioritySlider.setEnabled(false);
      priorityTextField.setText("0");
      
      Enumeration buttons = semanticsButtonGroup.getElements();
      while (buttons.hasMoreElements()){
         ((AbstractButton)buttons.nextElement()).setEnabled(true);
      }      
      
      priorityLabel.setEnabled(false);
      priorityPanel.setEnabled(false);

      RateParameter[] rates = pnmlData.getRateParameters();
      if (rates.length > 0) {
         rateComboBox.addItem("");
         for (int i = 0; i < rates.length; i++) {
            rateComboBox.addItem(rates[i]);
         }
      } else {
         rateComboBox.setEnabled(false);
      }      
   }
   
   
   private void immediateTransition(){
      immediateRadioButton.setSelected(true); 
      
      rateLabel.setText("Weight:");
      rateTextField.setText("" + transition.getRate());      
      
      prioritySlider.setEnabled(true);
      priorityTextField.setText("" + transition.getPriority());
      
      priorityLabel.setEnabled(true);
      priorityPanel.setEnabled(true);      

      RateParameter[] rates = pnmlData.getRateParameters();
      if (rates.length > 0) {
         rateComboBox.addItem("");
         for (int i = 0; i < rates.length; i++) {
            rateComboBox.addItem(rates[i]);
         }
      } else {
         rateComboBox.setEnabled(false);
      }            
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        semanticsButtonGroup = new javax.swing.ButtonGroup();
        transitionEditorPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        rateLabel = new javax.swing.JLabel();
        priorityLabel = new javax.swing.JLabel();
        attributesCheckBox = new javax.swing.JCheckBox();
        rateComboBox = new javax.swing.JComboBox();

        timedRadioButton = new javax.swing.JRadioButton();
        immediateRadioButton = new javax.swing.JRadioButton();
        serverPanel = new javax.swing.JPanel();
        singleServerRadioButton = new javax.swing.JRadioButton();
        infiniteServerRadioButton = new javax.swing.JRadioButton();
        rotationLabel = new javax.swing.JLabel();
        rotationComboBox = new javax.swing.JComboBox();
        rateTextField = new javax.swing.JTextField();
        serverLabel = new javax.swing.JLabel();
 
       
        priorityPanel = new javax.swing.JPanel();
        prioritySlider = new javax.swing.JSlider();
        priorityTextField = new javax.swing.JTextField();

        guardLabel = new javax.swing.JLabel();
        guardTextArea = new javax.swing.JTextArea();

        effectLabel = new javax.swing.JLabel();
        effectTextField = new javax.swing.JTextField();

        subnetFileLabel = new javax.swing.JLabel();
        subnetFileTextField = new javax.swing.JTextField();

        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        transitionEditorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(PipePrTLocales.bundleString("Edit Transition")));
//        transitionEditorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit transition "+transition.getId()));
        transitionEditorPanel.setLayout(new java.awt.GridBagLayout());

//        nameLabel.setText("Name:");
        nameLabel.setText(PipePrTLocales.bundleString("Event")+":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(nameLabel, gridBagConstraints);

        nameTextField.setText(transition.getName());
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(nameTextField, gridBagConstraints);

        guardLabel.setText(PipePrTLocales.bundleString("Guard")+":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(guardLabel, gridBagConstraints);

    	guardTextArea.setRows(3);
    	guardTextArea.setLineWrap(true);
   	
        int minCoulumn =30;
        guardTextArea.setText(transition.getGuard());
        if (transition.getName().length()<minCoulumn && 
        		transition.getGuard().length()<minCoulumn &&
        		transition.getEffect().length()<minCoulumn
        		)
        	guardTextArea.setColumns(minCoulumn);
        guardTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                guardTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                guardTextFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(new JScrollPane(guardTextArea), gridBagConstraints);

        effectLabel.setText(PipePrTLocales.bundleString("Effect")+":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(effectLabel, gridBagConstraints);

        effectTextField.setText(transition.getEffect());
        effectTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                effectTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                effectTextFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(effectTextField, gridBagConstraints);

        subnetFileLabel.setText(PipePrTLocales.bundleString("Subnet file")+":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(subnetFileLabel, gridBagConstraints);

        subnetFileTextField.setText(transition.getSubnetFile());
        subnetFileTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
            	subnetFileTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
            	subnetFileTextFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(subnetFileTextField, gridBagConstraints);

        attributesCheckBox.setSelected(transition.getAttributesVisible());
        attributesCheckBox.setText(PipePrTLocales.bundleString("Show transition attributes"));
        attributesCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        attributesCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(attributesCheckBox, gridBagConstraints);
        
        rotationLabel.setText(PipePrTLocales.bundleString("Rotation")+":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(rotationLabel, gridBagConstraints);

        rotationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "+45\u00B0", "+90\u00B0", "-45\u00B0" }));
        rotationComboBox.setMaximumSize(new java.awt.Dimension(70, 20));
        rotationComboBox.setMinimumSize(new java.awt.Dimension(70, 20));
        rotationComboBox.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        transitionEditorPanel.add(rotationComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(transitionEditorPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        cancelButton.setText(PipePrTLocales.bundleString("Cancel"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        buttonPanel.add(cancelButton, gridBagConstraints);

        okButton.setText(PipePrTLocales.bundleString("OK"));
        okButton.setMaximumSize(new java.awt.Dimension(75, 25));
        okButton.setMinimumSize(new java.awt.Dimension(75, 25));
        okButton.setPreferredSize(new java.awt.Dimension(75, 25));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonHandler(evt);
            }
        });
        okButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okButtonKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        buttonPanel.add(okButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 8, 3);
        add(buttonPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

   private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
      focusLost(nameTextField);
   }//GEN-LAST:event_nameTextFieldFocusLost

   private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
      focusGained(nameTextField);
   }//GEN-LAST:event_nameTextFieldFocusGained

   private void guardTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
	      focusLost(guardTextArea);
   }

   private void guardTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
	      focusGained(guardTextArea);
   }

   private void effectTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
	      focusLost(effectTextField);
   }

   private void effectTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
	      focusGained(effectTextField);
   }

   private void subnetFileTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
	      focusLost(subnetFileTextField);
   }

   private void subnetFileTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
	      focusGained(subnetFileTextField);
   }

   private void focusGained(javax.swing.JTextField textField){
      textField.setCaretPosition(0);
      textField.moveCaretPosition(textField.getText().length());
   }
   
   private void focusLost(javax.swing.JTextField textField){
      textField.setCaretPosition(0);
   }   

   private void focusGained(javax.swing.JTextArea textArea){
	      textArea.setCaretPosition(0);
	      textArea.moveCaretPosition(textArea.getText().length());
	   }
	   
   private void focusLost(javax.swing.JTextArea textArea){
	      textArea.setCaretPosition(0);
	   }   

   private void okButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okButtonKeyPressed
      if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
         okButtonHandler(new java.awt.event.ActionEvent(this,0,""));
      }
   }//GEN-LAST:event_okButtonKeyPressed


   CaretListener caretListener = new javax.swing.event.CaretListener() {
      public void caretUpdate(javax.swing.event.CaretEvent evt) {
         JTextField textField = (JTextField)evt.getSource();
         textField.setBackground(new Color(255,255,255));
         //textField.removeChangeListener(this);
      }
   };   
   
       
   private void okButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonHandler

	   if (subnetFileTextField.getText()!=null && !subnetFileTextField.getText().trim().equals("") && !PipeTransition.isValidSubnetFile(subnetFileTextField.getText())){
	    	JOptionPane.showMessageDialog(null,
	    			subnetFileTextField.getText()+": "+PipePrTLocales.bundleString("INVALID_SUBNET_FILE_NAME"), 
	    	        PipePrTLocales.bundleString("Error Message"),
	    	       JOptionPane.WARNING_MESSAGE);
	    	return;    	  
	   }

      view.getUndoManager().newEdit(); // new "transaction""
       
      String newName = nameTextField.getText();
      if (!newName.equals(name)){
//         if (pnmlData.checkTransitionIDAvailability(newName)){
            view.getUndoManager().addEdit(transition.setPNObjectName(newName));
/*         } else{
            // aquest nom no està disponible...
           JOptionPane.showMessageDialog(null,
                    "There is already a transition named " + newName, "Error",
                                JOptionPane.WARNING_MESSAGE);
            return;
         }
*/      }
      
      String newGuard = guardTextArea.getText();
      if (!newGuard.equals(transition.getGuard())){
    	  transition.setGuard(newGuard);
//            view.getUndoManager().addEdit(transition.setGuard(newGuard));
      }
      
      String newEffect = effectTextField.getText();
      if (!newEffect.equals(transition.getEffect())){
    	  transition.setEffect(newEffect);
//            view.getUndoManager().addEdit(transition.setEffect(newEffect));
      }

      String newSubnetFile = subnetFileTextField.getText();
      if (!newSubnetFile.equals(transition.getSubnetFile())){
    	  transition.setSubnetFile(newSubnetFile);
//            view.getUndoManager().addEdit(transition.setSubnetFile(newSubnetFile));
      }

      transition.setAttributesVisible(attributesCheckBox.isSelected());
      transition.updateAttributes();
/*      
      if (timedRadioButton.isSelected() != timed) {
         view.getUndoManager().addEdit(
                 transition.setTimed(!timed));
      }
      

      if (infiniteServerRadioButton.isSelected() != infiniteServer) {
         view.getUndoManager().addEdit(
                 transition.setInfiniteServer(!infiniteServer));
      }      
      
      int newPriority = prioritySlider.getValue();
      if (newPriority != priority && !transition.isTimed()) {
         view.getUndoManager().addEdit(transition.setPriority(newPriority));
      }
      
      if (rateComboBox.getSelectedIndex() > 0) {
         // There's a rate parameter selected
         RateParameter parameter = 
                 (RateParameter)rateComboBox.getSelectedItem() ;
         if (parameter != rParameter){

            if (rParameter != null) {
               // The rate parameter has been changed
               view.getUndoManager().addEdit(transition.changeRateParameter(
                       (RateParameter)rateComboBox.getSelectedItem()));
            } else {
               // The rate parameter has been changed
               view.getUndoManager().addEdit(transition.setRateParameter(
                       (RateParameter)rateComboBox.getSelectedItem()));
            }
         }
      } else {
         // There is no rate parameter selected
         if (rParameter != null) {
            // The rate parameter has been changed
            view.getUndoManager().addEdit(transition.clearRateParameter());
         }
         try{
            Double newRate = Double.parseDouble(rateTextField.getText());
            if (!newRate.equals(rate)) {
               view.getUndoManager().addEdit(transition.setRate(newRate));
            }
         } catch (NumberFormatException nfe){
            rateTextField.setBackground(new Color(255,0,0));
            rateTextField.addCaretListener(caretListener);
            return;
         } catch (Exception e){
            System.out.println(":" + e);
         }
      } 

      if (attributesVisible != attributesCheckBox.isSelected()){
         transition.toggleAttributesVisible();
      }      
*/
      Integer rotationIndex = rotationComboBox.getSelectedIndex();
      if (rotationIndex > 0) {
         int angle = 0;
         switch (rotationIndex) {
            case 1:
               angle = 45;
               break;
            case 2:
               angle = 90;
               break;
            case 3:
               angle = 135; //-45
               break;
            default:
               break;               
         }
         if (angle != 0) {
            view.getUndoManager().addEdit(transition.rotate(angle));
         }
      }

      transition.repaint();
      exit();
   }//GEN-LAST:event_okButtonHandler

   private void exit() {
      rootPane.getParent().setVisible(false);
   }
   
   
   private void cancelButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonHandler
      //Provisional!
      exit();
   }//GEN-LAST:event_cancelButtonHandler
      
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox attributesCheckBox;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton immediateRadioButton;
    private javax.swing.JRadioButton infiniteServerRadioButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JPanel priorityPanel;
    private javax.swing.JSlider prioritySlider;
    private javax.swing.JTextField priorityTextField;
    private javax.swing.JComboBox rateComboBox;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JComboBox rotationComboBox;
    private javax.swing.JLabel rotationLabel;
    private javax.swing.ButtonGroup semanticsButtonGroup;
    private javax.swing.JLabel serverLabel;
    private javax.swing.JPanel serverPanel;
    private javax.swing.JRadioButton singleServerRadioButton;
    private javax.swing.JRadioButton timedRadioButton;

    private javax.swing.JPanel transitionEditorPanel;
    // End of variables declaration//GEN-END:variables
   
    private javax.swing.JLabel guardLabel;
    private javax.swing.JTextArea guardTextArea;
    
    private javax.swing.JLabel effectLabel;
    private javax.swing.JTextField effectTextField;
    
    private javax.swing.JLabel subnetFileLabel;
    private javax.swing.JTextField subnetFileTextField;

}
